//! FFI bindings to ARPACK-NG.
//!
//! The bindings are pre-generated by `bindgen` against `<arpack/arpack.h>`
//! from ARPACK-NG (the `_c` C-callable wrappers introduced in 3.8.0).
//! Linking is handled by `build.rs` via `pkg-config`.
//!
//! No safety wrappers live here — see the sibling `arpack` crate for the
//! safe Rust API.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

include!("bindings.rs");
