//! FFI bindings to ARPACK-NG.
//!
//! The bindings are pre-generated by `bindgen` against `<arpack/arpack.h>`
//! from ARPACK-NG (the `_c` C-callable wrappers introduced in 3.8.0).
//! Linking is handled by `build.rs` via `pkg-config`.
//!
//! No safety wrappers live here — see the sibling `arpack` crate for the
//! safe Rust API.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// 32-bit-pointer-width targets are out of scope: workspace-size
// arithmetic in the safe wrapper is bounded only by `usize` /
// `isize::MAX`, and ARPACK use cases on 32-bit are not part of the
// supported envelope. Open an issue if 32-bit support is needed.
#[cfg(not(target_pointer_width = "64"))]
compile_error!("arpack-sys is supported only on 64-bit-pointer-width targets");

include!("bindings.rs");
